### ISSUE TITLE
Pyramid upsampling in the u-2net model 

### ISSUE THREAD

**Issue by advaza** [patrickisroman/u2net-tensorflow#1]
Hi 
Thanks for sharing your code.
I saw that you use pyramid upsampling where you use the upsampling layer multiple times instead of single time for every side output tensor. Wanted to ask why did you choose to implement like so?
Thanks 
Adva

**Comment by patrickisroman** [comment]
Hi Adva,

Thank you for pointing that out.

I reused the upsampling layers from the network levels to iteratively apply 2x2 bilinear upsampling until the side output matches the desired output size, just as a shortcut to save time when I was writing. I just tested with creating separate upsampling layers of sizes 2x2, 4x4, 8x8, 16x16, and 32x32, so that each side output only has a single upsampling applied to reach the network output size, which is how it is done in the original code, and the results are similar. 

To keep the graph clean, [I replaced these](https://github.com/patrickisroman/u2net-tensorflow/commit/6d76cab692a676b751f55dd4cad62eda321dea96) with the individual upsamples per your comment. Thanks!
